apiVersion: v2
name: ${{ values.name }}
description: A Helm chart for Kubernetes
type: application
version: 1
appVersion: "0.1.0"
dependencies:
- name: paradis-charts
  version: 0.1.0
  repository: https://github.com/igordevopslabs/paradis-charts