createDeployment: true

containerPort: true

replicaCount: 1

container:
  image:
    repository: ${{ values.name }}
    pullPolicy: IfNotPresent
    tag: "latest"
  port: "8080"

resources: {}

service:
  type: ClusterIP
  port: ${{ values.port }}