name: guardrails validate for helm values for ${{ values.name }}

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    uses: stone-payments/platform-k8s-github-actions/.github/workflows/guardrails_validate.yml@main
    secrets: inherit