apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: log-message-template
  title: Log Message Template
  description: Logs a custom message during scaffolding
spec:
  owner: log-message
  type: service
  
  steps:
    - id: log-custom-message
      name: Log a custom message
      action: debug:log
      input:
        message: "Logging the custom message: ${{ parameters.message }}"

  parameters:
    - title: Write some message
      required:
        - message
      properties:
        message:
          title: Message
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5