apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: log-message-template
  title: Log Message Template
  description: Logs a custom message during scaffolding
spec:
  owner: log-message
  type: service
  
  steps:
    - id: log-custom-message
      name: Log a custom message
      action: debug:log
      input:
        message: "Logging the custom message: {{ parameters.message }}"

  parameters:
    - title: message
      required: [message]
      properties:
        message:
          title: Mensagem a ser exibida
          type: string
          description: "EX: Oi, meu nome é Goku"