apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {% if values.context == 'payments' -%}
  name: pay-${{ values.name }}-${{ values.env }}
  {%- elseif values.context == 'foundation-platform' -%}
  name: fp-${{ values.name }}-${{ values.env }}
  {%- elseif values.context == 'data-platform' -%}
  name: dpl-${{ values.name }}-${{ values.env }}
  {%- elseif values.context == 'customer-platforms' -%}
  name: cpl-${{ values.name }}-${{ values.env }}
  {%- elseif values.context == 'credit' -%}
  name: crt-${{ values.name }}-${{ values.env }}
  {%- elseif values.context == 'finance-controllership' -%}
  name: fcl-${{ values.name }}-${{ values.env }}
  {%- elseif values.context == 'finance-treasury' -%}
  name: ftr-${{ values.name }}-${{ values.env }}
  {%- elseif values.context == 'payments-finance' -%}
  name: payf-${{ values.name }}-${{ values.env }}
  {%- endif %}
  namespace: argocd
  labels:
    {% if values.env == 'stg' -%}
    env: staging
    {%- elseif values.env == 'sdx' -%}
    env: sandbox
    {%- elseif values.env != 'stg' or values.env != 'sdx' -%}
    env: production
    {%- endif %}
    {% if values.context == 'payments' -%}
    cluster: runtime-${{ values.env }}
    {%- elseif values.context == 'foundation-platform' and values.env == 'stg' -%}
    cluster: runtime-tools-stg
    {%- elseif values.context == 'foundation-platform' and values.env != 'stg' -%}
    cluster: runtime-tools-prd
    {%- elseif values.context == 'data-platform' and values.env == 'stg' -%}
    cluster: runtime-data-platform-stg
    {%- elseif values.context == 'data-platform' and values.env != 'stg' -%}
    cluster: runtime-data-platform-prd
    {%- elseif values.context == 'customer-platforms' and values.env == 'stg' -%}
    cluster: runtime-customer-platforms-stg
    {%- elseif values.context == 'customer-platforms' and values.env != 'stg' -%}
    cluster: runtime-customer-platforms-prd
    {%- elseif values.context == 'credit' and values.env == 'stg' -%}
    cluster: runtime-aks-credit-eastus2-stg
    {%- elseif values.context == 'credit' and values.env == 'prd' -%}
    cluster: runtime-aks-credit-eastus2-prd
    {%- elseif values.context == 'credit' and values.env == 'dr' -%}
    cluster: runtime-aks-credit-centralus-prd
    {%- elseif values.context == 'finance-controllership' and values.env == 'stg' -%}
    cluster: runtime-aks-ctr-nonprod
    {%- elseif values.context == 'finance-controllership' and values.env == 'dr' -%}
    cluster: runtime-aks-ctr-dr
    {%- elseif values.context == 'finance-controllership' and values.env == 'prd' -%}
    cluster: runtime-aks-ctr-prod
    {%- elseif values.context == 'finance-treasury' and values.env == 'stg' -%}
    cluster: runtime-aks-trs-nonprod
    {%- elseif values.context == 'finance-treasury' and values.env == 'dr' -%}
    cluster: runtime-aks-trs-dr
    {%- elseif values.context == 'finance-treasury' and values.env == 'prd' -%}
    cluster: runtime-aks-trs-prod
    {%- elseif values.context == 'payments-finance' and values.env == 'stg' -%}
    cluster: runtime-aks-pro-ins-nonprod
    {%- elseif values.context == 'payments-finance' and values.env == 'dr' -%}
    cluster: runtime-aks-pro-ins-dr
    {%- elseif values.context == 'payments-finance' and values.env == 'prd' -%}
    cluster: runtime-aks-pro-ins-prod
    {%- endif %}
spec:
  {% if values.context == 'payments' -%}
  project: pay-${{ values.name }}
  {%- elseif values.context == 'foundation-platform' -%}
  project: fp-${{ values.name }}
  {%- elseif values.context == 'data-platform' -%}
  project: dpl-${{ values.name }}
  {%- elseif values.context == 'customer-platforms' -%}
  project: cpl-${{ values.name }}
  {%- elseif values.context == 'credit' -%}
  project: crt-${{ values.name }}
  {%- elseif values.context == 'finance-controllership' -%}
  project: fcl-${{ values.name }}
  {%- elseif values.context == 'finance-treasury' -%}
  project: ftr-${{ values.name }}
  {%- elseif values.context == 'payments-finance' -%}
  project: payf-${{ values.name }}
  {%- endif %}
  source:
    repoURL: 'https://${{ values.repoHost }}/${{ values.repoOwner }}/${{ values.repoName }}'
    path: chart
    {% if values.env == 'stg' -%}
    targetRevision: develop
    {%- elseif values.env != 'stg' -%}
    targetRevision: main
    {%- endif %}
    helm:
      parameters:
        - name: platform-k8s-api-chart.github.lastCommitSha
          value: $ARGOCD_APP_REVISION
        - name: platform-k8s-api-chart.github.repositoryUrl
          value: '${{ values.repoHost }}/${{ values.repoOwner }}/${{ values.repoName }}'
        {% if values.provider == 'aws' -%}
        - name: platform-k8s-api-chart.ingress.class
          value: "ingress-nginx"
        - name: platform-k8s-api-chart.cloudProviders.aws.enabled
          value: "true"
        - name: platform-k8s-api-chart.cloudProviders.aws.karpenter.enabled
          value: "true"
        - name: platform-k8s-api-chart.secrets.path
          value: ${{ values.name }}
        - name: platform-k8s-api-chart.datadog.enabled
          value: "true"
        - name: 'platform-k8s-api-chart.tolerations[0].effect'
          value: NoSchedule
        - name: 'platform-k8s-api-chart.tolerations[0].operator'
          value: Exists
        - name: platform-k8s-api-chart.secrets.secretStore.name
          value: cluster-secret-store-vault
        {%- elseif values.provider == 'azure' -%}
        - name: platform-k8s-api-chart.ingress.class
          value: "ingress-nginx-internal"
        - name: platform-k8s-api-chart.cloudProviders.azure.enabled
          value: "true"
        - name: platform-k8s-api-chart.cloudProviders.azure.imagePullSecrets.name
          value: "foundation-ecr-secret"
        - name: platform-k8s-api-chart.secrets.path
          value: ${{ values.name }}
        - name: platform-k8s-api-chart.datadog.enabled
          value: "false"
        - name: platform-k8s-api-chart.secrets.secretStore.name
          {% if values.env == 'stg' -%}
          value: foundation-stg-vault
          {%- elseif values.env != 'stg' -%}
          value: foundation-prd-vault
          {%- endif %}
        {%- endif %}
        {% if values.provider == 'aws' and values.context == 'payments' -%}
        - name: platform-k8s-api-chart.nodeSelector.purpose
          value: payments
        - name: 'platform-k8s-api-chart.tolerations[0].key'
          value: payments
        - name: platform-k8s-api-chart.cloudProviders.aws.karpenter.selector
          value: payments
        - name: platform-k8s-api-chart.secrets.kv
          value: ${{ values.env }}
        {%- elseif values.provider == 'aws' and values.context == 'customer-platforms' -%}
        - name: platform-k8s-api-chart.nodeSelector.purpose
          value: customer-platforms
        - name: 'platform-k8s-api-chart.tolerations[0].key'
          value: customer-platforms
        - name: platform-k8s-api-chart.cloudProviders.aws.karpenter.selector
          value: customer-platforms
        - name: platform-k8s-api-chart.secrets.kv
          {% if values.env == 'stg' -%}
          value: customer-platforms-stg
          {%- elseif values.env != 'stg' -%}
          value: customer-platforms-prd
          {%- endif %}
        {%- elseif values.provider == 'aws' and values.context == 'data-platform' -%}
        - name: platform-k8s-api-chart.nodeSelector.purpose
          value: data
        - name: 'platform-k8s-api-chart.tolerations[0].key'
          value: data
        - name: platform-k8s-api-chart.cloudProviders.aws.karpenter.selector
          value: data
        - name: platform-k8s-api-chart.secrets.kv
          {% if values.env == 'stg' -%}
          value: data-platform-stg
          {%- elseif values.env != 'stg' -%}
          value: data-platform-prd
          {%- endif %}
        {%- elseif values.provider == 'aws' and values.context == 'foundation-platform' -%}
        - name: platform-k8s-api-chart.nodeSelector.purpose
          value: foundation
        - name: 'platform-k8s-api-chart.tolerations[0].key'
          value: foundation
        - name: platform-k8s-api-chart.cloudProviders.aws.karpenter.selector
          value: foundation
        - name: platform-k8s-api-chart.secrets.kv
          {% if values.env == 'stg' -%}
          value: tools-stg
          {%- elseif values.env != 'stg' -%}
          value: tools-prd
          {%- endif %}
        {%- elseif values.provider == 'azure' and values.context == 'credit' -%}
        - name: platform-k8s-api-chart.secrets.kv
          {% if values.env == 'stg' -%}
          value: credit-stg
          {%- elseif values.env != 'stg' -%}
          value: credit-prd
          {%- endif %}
        {%- elseif values.provider == 'azure' and values.context == 'finance-controllership' -%}
        - name: platform-k8s-api-chart.secrets.kv
          {% if values.env == 'stg' -%}
          value: ctr-stg
          {%- elseif values.env != 'stg' -%}
          value: ctr-prd
          {%- endif %}
        {%- elseif values.provider == 'azure' and values.context == 'finance-treasury' -%}
        - name: platform-k8s-api-chart.secrets.kv
          {% if values.env == 'stg' -%}
          value: trs-stg
          {%- elseif values.env != 'stg' -%}
          value: trs-prd
          {%- endif %}
        {%- elseif values.provider == 'azure' and values.context == 'payments-finance' -%}
        - name: platform-k8s-api-chart.secrets.kv
          {% if values.env == 'stg' -%}
          value: pro-ins-stg
          {%- elseif values.env != 'stg' -%}
          value: pro-ins-prd
          {%- endif %}
        {%- endif %}
      valueFiles:
        - values-${{ values.env }}.yaml
  destination:
    namespace: app-${{ values.name }}
    {% if values.context == 'payments' -%}
    name: runtime-${{ values.env }}
    {%- elseif values.context == 'foundation-platform' and values.env == 'stg' -%}
    name: runtime-tools-stg
    {%- elseif values.context == 'foundation-platform' and values.env != 'stg' -%}
    name: runtime-tools-prd
    {%- elseif values.context == 'data-platform' and values.env == 'stg' -%}
    name: runtime-data-platform-stg
    {%- elseif values.context == 'data-platform' and values.env != 'stg' -%}
    name: runtime-data-platform-prd
    {%- elseif values.context == 'customer-platforms' and values.env == 'stg' -%}
    name: runtime-customer-platforms-stg
    {%- elseif values.context == 'customer-platforms' and values.env != 'stg' -%}
    name: runtime-customer-platforms-prd
    {%- elseif values.context == 'credit' and values.env == 'stg' -%}
    name: runtime-aks-credit-eastus2-stg
    {%- elseif values.context == 'credit' and values.env == 'prd' -%}
    name: runtime-aks-credit-eastus2-prd
    {%- elseif values.context == 'credit' and values.env == 'dr' -%}
    name: runtime-aks-credit-centralus-prd
    {%- elseif values.context == 'finance-controllership' and values.env == 'stg' -%}
    name: runtime-aks-ctr-nonprod
    {%- elseif values.context == 'finance-controllership' and values.env == 'dr' -%}
    name: runtime-aks-ctr-dr
    {%- elseif values.context == 'finance-controllership' and values.env == 'prd' -%}
    name: runtime-aks-ctr-prod
    {%- elseif values.context == 'finance-treasury' and values.env == 'stg' -%}
    name: runtime-aks-trs-nonprod
    {%- elseif values.context == 'finance-treasury' and values.env == 'dr' -%}
    name: runtime-aks-trs-dr
    {%- elseif values.context == 'finance-treasury' and values.env == 'prd' -%}
    name: runtime-aks-trs-prod
    {%- elseif values.context == 'payments-finance' and values.env == 'stg' -%}
    name: runtime-aks-pro-ins-nonprod
    {%- elseif values.context == 'payments-finance' and values.env == 'dr' -%}
    name: runtime-aks-pro-ins-dr
    {%- elseif values.context == 'payments-finance' and values.env == 'prd' -%}
    name: runtime-aks-pro-ins-prod
    {%- endif %}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
