apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: go-helloworld-template
  title: Go Hello World Template
  description: Creates a Go application that prints "Hello, World!" and publishes it to GitHub
spec:
  owner: go-helloworld
  type: service

  parameters:
    - title: Data of project
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the Go project
          ui:autofocus: true
    - title: Ownership
      required:
        - organization
      properties:
        organization:
          title: organization
          type: string
          description: Github organition, default igordevopslabs
          default: igordevopslabs
          ui:autofocus: true

  steps:

    - id: fetch-base
      name: Fetch Local Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}

    - id: fetch-base
      name: Fetch base remote template
      action: fetch:plain
      input:
        url: https://github.com/igordevopslabs/go-app-template.git

    - id: publish-github
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=igordevopslabs&repo=${{ parameters.name }}
        description: 'Go application that prints "Hello, World!"'
        access: public # or 'private'
        defaultBranch: main

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-github'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
        
  # some outputs which are saved along with the job for use in the frontend
  output:
    links:
      - title: Repository
        url: ${{ steps['fetch-base'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}